name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history so we can switch branches
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Adjust as needed
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Commit and push to pub branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          # Create worktree for pub branch
          git fetch origin pub || true
          git worktree add ../pub pub || git worktree add ../pub -b pub origin/master
      
          # Copy built site into pub
          rm -rf ../pub/*
          cp -r _site/* ../pub/
      
          cd ../pub
          git add .
          git commit -m "chore: generate a static site" || echo "Nothing to commit"
      
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin pub --force
